// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: Protoc.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace GameProto {

  /// <summary>Holder for reflection information generated from Protoc.proto</summary>
  public static partial class ProtocReflection {

    #region Descriptor
    /// <summary>File descriptor for Protoc.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static ProtocReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "CgxQcm90b2MucHJvdG8SCUdhbWVQcm90byIrCghQb3NpdGlvbhIJCgF4GAEg",
            "ASgCEgkKAXkYAiABKAISCQoBehgDIAEoAiJmCgtQbGF5ZXJTdGF0ZRILCgNm",
            "aWQYASABKAUSDAoEbmFtZRgCIAEoCRILCgN5YXcYAyABKAISIAoDcG9zGAQg",
            "ASgLMhMuR2FtZVByb3RvLlBvc2l0aW9uEg0KBXN0YXRlGAUgASgFIkoKC1Bs",
            "YXllcklucHV0EgwKBG5hbWUYASABKAkSDgoGdG9ycXVlGAIgASgCEg0KBWdy",
            "YXNwGAMgASgIEg4KBmF0dGFjaBgEIAEoCCI5CghSb29tSW5mbxIKCgJpZBgB",
            "IAEoBRIQCghtYXh1c2VycxgCIAEoBRIPCgdtZW1iZXJzGAMgAygJIogBCglD",
            "bGllbnRNc2cSKAoEdHlwZRgBIAEoDjIaLkdhbWVQcm90by5DbGllbnRFdmVu",
            "dENvZGUSDAoEbmFtZRgCIAEoCRIQCghwYXNzd29yZBgDIAEoCRIKCgJpZBgE",
            "IAEoBRIlCgVpbnB1dBgFIAEoCzIWLkdhbWVQcm90by5QbGF5ZXJJbnB1dCLH",
            "AQoJU2VydmVyTXNnEigKBHR5cGUYASABKA4yGi5HYW1lUHJvdG8uU2VydmVy",
            "RXZlbnRDb2RlEgsKA2ZpZBgCIAEoBRILCgNzdHIYAyABKAkSJgoGaW5wdXRz",
            "GAQgAygLMhYuR2FtZVByb3RvLlBsYXllcklucHV0EiYKBnN0YXRlcxgFIAMo",
            "CzIWLkdhbWVQcm90by5QbGF5ZXJTdGF0ZRImCglyb29taW5mb3MYBiADKAsy",
            "Ey5HYW1lUHJvdG8uUm9vbUluZm8q1AIKD1NlcnZlckV2ZW50Q29kZRIQCgxM",
            "b2dJblN1Y2Nlc3MQABITCg9SZWdpc3RlclN1Y2Nlc3MQARIUChBFbnRlclJv",
            "b21TdWNjZXNzEAISHwobTG9nSW5FcnJvcl9BY2NvdW50RG9udEV4aXN0EAMS",
            "HAoYTG9nSW5FcnJvcl9QYXNzd29yZFdyb25nEAQSFgoSTG9nSW5FcnJvcl9S",
            "ZUxvZ0luEAUSJQohUmVnaXN0ZXJFcnJvcl9BY2NvdW50QWxyZWFkeUV4aXN0",
            "EAYSHAoYRW50ZXJSb29tRXJyb3JfRG9udExvZ0luEAcSHQoZRW50ZXJSb29t",
            "RXJyb3JfUm9vbUlzRnVsbBAIEhEKDUludGVybmFsRXJyb3IQCRIRCg1Ccm9h",
            "ZFJvb21JbmZvEAoSFgoSSnVtcFRvQmF0dGxlU2VydmVyEAsSCwoHUzJDU3lu",
            "YxAMKlAKD0NsaWVudEV2ZW50Q29kZRIJCgVMb2dJbhAAEgoKBlJlZ2lzdBAB",
            "Eg0KCUVudGVyUm9vbRACEgsKB0MyU1N5bmMQAxIKCgZGb2xsb3cQBGIGcHJv",
            "dG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::GameProto.ServerEventCode), typeof(global::GameProto.ClientEventCode), }, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::GameProto.Position), global::GameProto.Position.Parser, new[]{ "X", "Y", "Z" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::GameProto.PlayerState), global::GameProto.PlayerState.Parser, new[]{ "Fid", "Name", "Yaw", "Pos", "State" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::GameProto.PlayerInput), global::GameProto.PlayerInput.Parser, new[]{ "Name", "Torque", "Grasp", "Attach" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::GameProto.RoomInfo), global::GameProto.RoomInfo.Parser, new[]{ "Id", "Maxusers", "Members" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::GameProto.ClientMsg), global::GameProto.ClientMsg.Parser, new[]{ "Type", "Name", "Password", "Id", "Input" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::GameProto.ServerMsg), global::GameProto.ServerMsg.Parser, new[]{ "Type", "Fid", "Str", "Inputs", "States", "Roominfos" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Enums
  /// <summary>
  ///S2C
  /// </summary>
  public enum ServerEventCode {
    [pbr::OriginalName("LogInSuccess")] LogInSuccess = 0,
    [pbr::OriginalName("RegisterSuccess")] RegisterSuccess = 1,
    [pbr::OriginalName("EnterRoomSuccess")] EnterRoomSuccess = 2,
    [pbr::OriginalName("LogInError_AccountDontExist")] LogInErrorAccountDontExist = 3,
    [pbr::OriginalName("LogInError_PasswordWrong")] LogInErrorPasswordWrong = 4,
    [pbr::OriginalName("LogInError_ReLogIn")] LogInErrorReLogIn = 5,
    [pbr::OriginalName("RegisterError_AccountAlreadyExist")] RegisterErrorAccountAlreadyExist = 6,
    [pbr::OriginalName("EnterRoomError_DontLogIn")] EnterRoomErrorDontLogIn = 7,
    [pbr::OriginalName("EnterRoomError_RoomIsFull")] EnterRoomErrorRoomIsFull = 8,
    [pbr::OriginalName("InternalError")] InternalError = 9,
    [pbr::OriginalName("BroadRoomInfo")] BroadRoomInfo = 10,
    [pbr::OriginalName("JumpToBattleServer")] JumpToBattleServer = 11,
    [pbr::OriginalName("S2CSync")] S2Csync = 12,
  }

  /// <summary>
  ///C2S
  /// </summary>
  public enum ClientEventCode {
    [pbr::OriginalName("LogIn")] LogIn = 0,
    [pbr::OriginalName("Regist")] Regist = 1,
    [pbr::OriginalName("EnterRoom")] EnterRoom = 2,
    [pbr::OriginalName("C2SSync")] C2Ssync = 3,
    [pbr::OriginalName("Follow")] Follow = 4,
  }

  #endregion

  #region Messages
  public sealed partial class Position : pb::IMessage<Position> {
    private static readonly pb::MessageParser<Position> _parser = new pb::MessageParser<Position>(() => new Position());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<Position> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::GameProto.ProtocReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Position() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Position(Position other) : this() {
      x_ = other.x_;
      y_ = other.y_;
      z_ = other.z_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Position Clone() {
      return new Position(this);
    }

    /// <summary>Field number for the "x" field.</summary>
    public const int XFieldNumber = 1;
    private float x_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public float X {
      get { return x_; }
      set {
        x_ = value;
      }
    }

    /// <summary>Field number for the "y" field.</summary>
    public const int YFieldNumber = 2;
    private float y_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public float Y {
      get { return y_; }
      set {
        y_ = value;
      }
    }

    /// <summary>Field number for the "z" field.</summary>
    public const int ZFieldNumber = 3;
    private float z_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public float Z {
      get { return z_; }
      set {
        z_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as Position);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(Position other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.Equals(X, other.X)) return false;
      if (!pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.Equals(Y, other.Y)) return false;
      if (!pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.Equals(Z, other.Z)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (X != 0F) hash ^= pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.GetHashCode(X);
      if (Y != 0F) hash ^= pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.GetHashCode(Y);
      if (Z != 0F) hash ^= pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.GetHashCode(Z);
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (X != 0F) {
        output.WriteRawTag(13);
        output.WriteFloat(X);
      }
      if (Y != 0F) {
        output.WriteRawTag(21);
        output.WriteFloat(Y);
      }
      if (Z != 0F) {
        output.WriteRawTag(29);
        output.WriteFloat(Z);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (X != 0F) {
        size += 1 + 4;
      }
      if (Y != 0F) {
        size += 1 + 4;
      }
      if (Z != 0F) {
        size += 1 + 4;
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(Position other) {
      if (other == null) {
        return;
      }
      if (other.X != 0F) {
        X = other.X;
      }
      if (other.Y != 0F) {
        Y = other.Y;
      }
      if (other.Z != 0F) {
        Z = other.Z;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 13: {
            X = input.ReadFloat();
            break;
          }
          case 21: {
            Y = input.ReadFloat();
            break;
          }
          case 29: {
            Z = input.ReadFloat();
            break;
          }
        }
      }
    }

  }

  /// <summary>
  ///玩家状态
  /// </summary>
  public sealed partial class PlayerState : pb::IMessage<PlayerState> {
    private static readonly pb::MessageParser<PlayerState> _parser = new pb::MessageParser<PlayerState>(() => new PlayerState());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<PlayerState> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::GameProto.ProtocReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public PlayerState() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public PlayerState(PlayerState other) : this() {
      fid_ = other.fid_;
      name_ = other.name_;
      yaw_ = other.yaw_;
      pos_ = other.pos_ != null ? other.pos_.Clone() : null;
      state_ = other.state_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public PlayerState Clone() {
      return new PlayerState(this);
    }

    /// <summary>Field number for the "fid" field.</summary>
    public const int FidFieldNumber = 1;
    private int fid_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int Fid {
      get { return fid_; }
      set {
        fid_ = value;
      }
    }

    /// <summary>Field number for the "name" field.</summary>
    public const int NameFieldNumber = 2;
    private string name_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Name {
      get { return name_; }
      set {
        name_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "yaw" field.</summary>
    public const int YawFieldNumber = 3;
    private float yaw_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public float Yaw {
      get { return yaw_; }
      set {
        yaw_ = value;
      }
    }

    /// <summary>Field number for the "pos" field.</summary>
    public const int PosFieldNumber = 4;
    private global::GameProto.Position pos_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::GameProto.Position Pos {
      get { return pos_; }
      set {
        pos_ = value;
      }
    }

    /// <summary>Field number for the "state" field.</summary>
    public const int StateFieldNumber = 5;
    private int state_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int State {
      get { return state_; }
      set {
        state_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as PlayerState);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(PlayerState other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Fid != other.Fid) return false;
      if (Name != other.Name) return false;
      if (!pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.Equals(Yaw, other.Yaw)) return false;
      if (!object.Equals(Pos, other.Pos)) return false;
      if (State != other.State) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (Fid != 0) hash ^= Fid.GetHashCode();
      if (Name.Length != 0) hash ^= Name.GetHashCode();
      if (Yaw != 0F) hash ^= pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.GetHashCode(Yaw);
      if (pos_ != null) hash ^= Pos.GetHashCode();
      if (State != 0) hash ^= State.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (Fid != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(Fid);
      }
      if (Name.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(Name);
      }
      if (Yaw != 0F) {
        output.WriteRawTag(29);
        output.WriteFloat(Yaw);
      }
      if (pos_ != null) {
        output.WriteRawTag(34);
        output.WriteMessage(Pos);
      }
      if (State != 0) {
        output.WriteRawTag(40);
        output.WriteInt32(State);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (Fid != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Fid);
      }
      if (Name.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Name);
      }
      if (Yaw != 0F) {
        size += 1 + 4;
      }
      if (pos_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Pos);
      }
      if (State != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(State);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(PlayerState other) {
      if (other == null) {
        return;
      }
      if (other.Fid != 0) {
        Fid = other.Fid;
      }
      if (other.Name.Length != 0) {
        Name = other.Name;
      }
      if (other.Yaw != 0F) {
        Yaw = other.Yaw;
      }
      if (other.pos_ != null) {
        if (pos_ == null) {
          Pos = new global::GameProto.Position();
        }
        Pos.MergeFrom(other.Pos);
      }
      if (other.State != 0) {
        State = other.State;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            Fid = input.ReadInt32();
            break;
          }
          case 18: {
            Name = input.ReadString();
            break;
          }
          case 29: {
            Yaw = input.ReadFloat();
            break;
          }
          case 34: {
            if (pos_ == null) {
              Pos = new global::GameProto.Position();
            }
            input.ReadMessage(Pos);
            break;
          }
          case 40: {
            State = input.ReadInt32();
            break;
          }
        }
      }
    }

  }

  /// <summary>
  ///玩家一次操作
  /// </summary>
  public sealed partial class PlayerInput : pb::IMessage<PlayerInput> {
    private static readonly pb::MessageParser<PlayerInput> _parser = new pb::MessageParser<PlayerInput>(() => new PlayerInput());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<PlayerInput> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::GameProto.ProtocReflection.Descriptor.MessageTypes[2]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public PlayerInput() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public PlayerInput(PlayerInput other) : this() {
      name_ = other.name_;
      torque_ = other.torque_;
      grasp_ = other.grasp_;
      attach_ = other.attach_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public PlayerInput Clone() {
      return new PlayerInput(this);
    }

    /// <summary>Field number for the "name" field.</summary>
    public const int NameFieldNumber = 1;
    private string name_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Name {
      get { return name_; }
      set {
        name_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "torque" field.</summary>
    public const int TorqueFieldNumber = 2;
    private float torque_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public float Torque {
      get { return torque_; }
      set {
        torque_ = value;
      }
    }

    /// <summary>Field number for the "grasp" field.</summary>
    public const int GraspFieldNumber = 3;
    private bool grasp_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Grasp {
      get { return grasp_; }
      set {
        grasp_ = value;
      }
    }

    /// <summary>Field number for the "attach" field.</summary>
    public const int AttachFieldNumber = 4;
    private bool attach_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Attach {
      get { return attach_; }
      set {
        attach_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as PlayerInput);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(PlayerInput other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Name != other.Name) return false;
      if (!pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.Equals(Torque, other.Torque)) return false;
      if (Grasp != other.Grasp) return false;
      if (Attach != other.Attach) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (Name.Length != 0) hash ^= Name.GetHashCode();
      if (Torque != 0F) hash ^= pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.GetHashCode(Torque);
      if (Grasp != false) hash ^= Grasp.GetHashCode();
      if (Attach != false) hash ^= Attach.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (Name.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Name);
      }
      if (Torque != 0F) {
        output.WriteRawTag(21);
        output.WriteFloat(Torque);
      }
      if (Grasp != false) {
        output.WriteRawTag(24);
        output.WriteBool(Grasp);
      }
      if (Attach != false) {
        output.WriteRawTag(32);
        output.WriteBool(Attach);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (Name.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Name);
      }
      if (Torque != 0F) {
        size += 1 + 4;
      }
      if (Grasp != false) {
        size += 1 + 1;
      }
      if (Attach != false) {
        size += 1 + 1;
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(PlayerInput other) {
      if (other == null) {
        return;
      }
      if (other.Name.Length != 0) {
        Name = other.Name;
      }
      if (other.Torque != 0F) {
        Torque = other.Torque;
      }
      if (other.Grasp != false) {
        Grasp = other.Grasp;
      }
      if (other.Attach != false) {
        Attach = other.Attach;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            Name = input.ReadString();
            break;
          }
          case 21: {
            Torque = input.ReadFloat();
            break;
          }
          case 24: {
            Grasp = input.ReadBool();
            break;
          }
          case 32: {
            Attach = input.ReadBool();
            break;
          }
        }
      }
    }

  }

  public sealed partial class RoomInfo : pb::IMessage<RoomInfo> {
    private static readonly pb::MessageParser<RoomInfo> _parser = new pb::MessageParser<RoomInfo>(() => new RoomInfo());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<RoomInfo> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::GameProto.ProtocReflection.Descriptor.MessageTypes[3]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public RoomInfo() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public RoomInfo(RoomInfo other) : this() {
      id_ = other.id_;
      maxusers_ = other.maxusers_;
      members_ = other.members_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public RoomInfo Clone() {
      return new RoomInfo(this);
    }

    /// <summary>Field number for the "id" field.</summary>
    public const int IdFieldNumber = 1;
    private int id_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int Id {
      get { return id_; }
      set {
        id_ = value;
      }
    }

    /// <summary>Field number for the "maxusers" field.</summary>
    public const int MaxusersFieldNumber = 2;
    private int maxusers_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int Maxusers {
      get { return maxusers_; }
      set {
        maxusers_ = value;
      }
    }

    /// <summary>Field number for the "members" field.</summary>
    public const int MembersFieldNumber = 3;
    private static readonly pb::FieldCodec<string> _repeated_members_codec
        = pb::FieldCodec.ForString(26);
    private readonly pbc::RepeatedField<string> members_ = new pbc::RepeatedField<string>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<string> Members {
      get { return members_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as RoomInfo);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(RoomInfo other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Id != other.Id) return false;
      if (Maxusers != other.Maxusers) return false;
      if(!members_.Equals(other.members_)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (Id != 0) hash ^= Id.GetHashCode();
      if (Maxusers != 0) hash ^= Maxusers.GetHashCode();
      hash ^= members_.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (Id != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(Id);
      }
      if (Maxusers != 0) {
        output.WriteRawTag(16);
        output.WriteInt32(Maxusers);
      }
      members_.WriteTo(output, _repeated_members_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (Id != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Id);
      }
      if (Maxusers != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Maxusers);
      }
      size += members_.CalculateSize(_repeated_members_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(RoomInfo other) {
      if (other == null) {
        return;
      }
      if (other.Id != 0) {
        Id = other.Id;
      }
      if (other.Maxusers != 0) {
        Maxusers = other.Maxusers;
      }
      members_.Add(other.members_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            Id = input.ReadInt32();
            break;
          }
          case 16: {
            Maxusers = input.ReadInt32();
            break;
          }
          case 26: {
            members_.AddEntriesFrom(input, _repeated_members_codec);
            break;
          }
        }
      }
    }

  }

  /// <summary>
  ///客户端数据包
  ///登录：type=LogIn,name,password
  ///注册：type=Regist,name,password
  ///进房间：type=EnterRoom,name,id=room_id
  ///同步：type=Sync,input
  ///追帧：type=Follow,name,id=fid
  /// </summary>
  public sealed partial class ClientMsg : pb::IMessage<ClientMsg> {
    private static readonly pb::MessageParser<ClientMsg> _parser = new pb::MessageParser<ClientMsg>(() => new ClientMsg());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<ClientMsg> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::GameProto.ProtocReflection.Descriptor.MessageTypes[4]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ClientMsg() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ClientMsg(ClientMsg other) : this() {
      type_ = other.type_;
      name_ = other.name_;
      password_ = other.password_;
      id_ = other.id_;
      input_ = other.input_ != null ? other.input_.Clone() : null;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ClientMsg Clone() {
      return new ClientMsg(this);
    }

    /// <summary>Field number for the "type" field.</summary>
    public const int TypeFieldNumber = 1;
    private global::GameProto.ClientEventCode type_ = global::GameProto.ClientEventCode.LogIn;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::GameProto.ClientEventCode Type {
      get { return type_; }
      set {
        type_ = value;
      }
    }

    /// <summary>Field number for the "name" field.</summary>
    public const int NameFieldNumber = 2;
    private string name_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Name {
      get { return name_; }
      set {
        name_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "password" field.</summary>
    public const int PasswordFieldNumber = 3;
    private string password_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Password {
      get { return password_; }
      set {
        password_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "id" field.</summary>
    public const int IdFieldNumber = 4;
    private int id_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int Id {
      get { return id_; }
      set {
        id_ = value;
      }
    }

    /// <summary>Field number for the "input" field.</summary>
    public const int InputFieldNumber = 5;
    private global::GameProto.PlayerInput input_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::GameProto.PlayerInput Input {
      get { return input_; }
      set {
        input_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as ClientMsg);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(ClientMsg other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Type != other.Type) return false;
      if (Name != other.Name) return false;
      if (Password != other.Password) return false;
      if (Id != other.Id) return false;
      if (!object.Equals(Input, other.Input)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (Type != global::GameProto.ClientEventCode.LogIn) hash ^= Type.GetHashCode();
      if (Name.Length != 0) hash ^= Name.GetHashCode();
      if (Password.Length != 0) hash ^= Password.GetHashCode();
      if (Id != 0) hash ^= Id.GetHashCode();
      if (input_ != null) hash ^= Input.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (Type != global::GameProto.ClientEventCode.LogIn) {
        output.WriteRawTag(8);
        output.WriteEnum((int) Type);
      }
      if (Name.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(Name);
      }
      if (Password.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(Password);
      }
      if (Id != 0) {
        output.WriteRawTag(32);
        output.WriteInt32(Id);
      }
      if (input_ != null) {
        output.WriteRawTag(42);
        output.WriteMessage(Input);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (Type != global::GameProto.ClientEventCode.LogIn) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) Type);
      }
      if (Name.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Name);
      }
      if (Password.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Password);
      }
      if (Id != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Id);
      }
      if (input_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Input);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(ClientMsg other) {
      if (other == null) {
        return;
      }
      if (other.Type != global::GameProto.ClientEventCode.LogIn) {
        Type = other.Type;
      }
      if (other.Name.Length != 0) {
        Name = other.Name;
      }
      if (other.Password.Length != 0) {
        Password = other.Password;
      }
      if (other.Id != 0) {
        Id = other.Id;
      }
      if (other.input_ != null) {
        if (input_ == null) {
          Input = new global::GameProto.PlayerInput();
        }
        Input.MergeFrom(other.Input);
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            Type = (global::GameProto.ClientEventCode) input.ReadEnum();
            break;
          }
          case 18: {
            Name = input.ReadString();
            break;
          }
          case 26: {
            Password = input.ReadString();
            break;
          }
          case 32: {
            Id = input.ReadInt32();
            break;
          }
          case 42: {
            if (input_ == null) {
              Input = new global::GameProto.PlayerInput();
            }
            input.ReadMessage(Input);
            break;
          }
        }
      }
    }

  }

  /// <summary>
  ///服务器数据包
  ///登录成功：type = LogInSuccess
  ///注册成功：type = RegistSuccess
  ///进房间成功：type = EnterRoomSuccess,fid=房间人数
  ///登录，注册，进房间失败：type=Failure,str
  ///跳转服务器: type=JumpToBattleServer,str=ip:port
  ///同步：type = Sync,fid,inputs,(states?)
  /// </summary>
  public sealed partial class ServerMsg : pb::IMessage<ServerMsg> {
    private static readonly pb::MessageParser<ServerMsg> _parser = new pb::MessageParser<ServerMsg>(() => new ServerMsg());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<ServerMsg> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::GameProto.ProtocReflection.Descriptor.MessageTypes[5]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ServerMsg() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ServerMsg(ServerMsg other) : this() {
      type_ = other.type_;
      fid_ = other.fid_;
      str_ = other.str_;
      inputs_ = other.inputs_.Clone();
      states_ = other.states_.Clone();
      roominfos_ = other.roominfos_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ServerMsg Clone() {
      return new ServerMsg(this);
    }

    /// <summary>Field number for the "type" field.</summary>
    public const int TypeFieldNumber = 1;
    private global::GameProto.ServerEventCode type_ = global::GameProto.ServerEventCode.LogInSuccess;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::GameProto.ServerEventCode Type {
      get { return type_; }
      set {
        type_ = value;
      }
    }

    /// <summary>Field number for the "fid" field.</summary>
    public const int FidFieldNumber = 2;
    private int fid_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int Fid {
      get { return fid_; }
      set {
        fid_ = value;
      }
    }

    /// <summary>Field number for the "str" field.</summary>
    public const int StrFieldNumber = 3;
    private string str_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Str {
      get { return str_; }
      set {
        str_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "inputs" field.</summary>
    public const int InputsFieldNumber = 4;
    private static readonly pb::FieldCodec<global::GameProto.PlayerInput> _repeated_inputs_codec
        = pb::FieldCodec.ForMessage(34, global::GameProto.PlayerInput.Parser);
    private readonly pbc::RepeatedField<global::GameProto.PlayerInput> inputs_ = new pbc::RepeatedField<global::GameProto.PlayerInput>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<global::GameProto.PlayerInput> Inputs {
      get { return inputs_; }
    }

    /// <summary>Field number for the "states" field.</summary>
    public const int StatesFieldNumber = 5;
    private static readonly pb::FieldCodec<global::GameProto.PlayerState> _repeated_states_codec
        = pb::FieldCodec.ForMessage(42, global::GameProto.PlayerState.Parser);
    private readonly pbc::RepeatedField<global::GameProto.PlayerState> states_ = new pbc::RepeatedField<global::GameProto.PlayerState>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<global::GameProto.PlayerState> States {
      get { return states_; }
    }

    /// <summary>Field number for the "roominfos" field.</summary>
    public const int RoominfosFieldNumber = 6;
    private static readonly pb::FieldCodec<global::GameProto.RoomInfo> _repeated_roominfos_codec
        = pb::FieldCodec.ForMessage(50, global::GameProto.RoomInfo.Parser);
    private readonly pbc::RepeatedField<global::GameProto.RoomInfo> roominfos_ = new pbc::RepeatedField<global::GameProto.RoomInfo>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<global::GameProto.RoomInfo> Roominfos {
      get { return roominfos_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as ServerMsg);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(ServerMsg other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Type != other.Type) return false;
      if (Fid != other.Fid) return false;
      if (Str != other.Str) return false;
      if(!inputs_.Equals(other.inputs_)) return false;
      if(!states_.Equals(other.states_)) return false;
      if(!roominfos_.Equals(other.roominfos_)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (Type != global::GameProto.ServerEventCode.LogInSuccess) hash ^= Type.GetHashCode();
      if (Fid != 0) hash ^= Fid.GetHashCode();
      if (Str.Length != 0) hash ^= Str.GetHashCode();
      hash ^= inputs_.GetHashCode();
      hash ^= states_.GetHashCode();
      hash ^= roominfos_.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (Type != global::GameProto.ServerEventCode.LogInSuccess) {
        output.WriteRawTag(8);
        output.WriteEnum((int) Type);
      }
      if (Fid != 0) {
        output.WriteRawTag(16);
        output.WriteInt32(Fid);
      }
      if (Str.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(Str);
      }
      inputs_.WriteTo(output, _repeated_inputs_codec);
      states_.WriteTo(output, _repeated_states_codec);
      roominfos_.WriteTo(output, _repeated_roominfos_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (Type != global::GameProto.ServerEventCode.LogInSuccess) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) Type);
      }
      if (Fid != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Fid);
      }
      if (Str.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Str);
      }
      size += inputs_.CalculateSize(_repeated_inputs_codec);
      size += states_.CalculateSize(_repeated_states_codec);
      size += roominfos_.CalculateSize(_repeated_roominfos_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(ServerMsg other) {
      if (other == null) {
        return;
      }
      if (other.Type != global::GameProto.ServerEventCode.LogInSuccess) {
        Type = other.Type;
      }
      if (other.Fid != 0) {
        Fid = other.Fid;
      }
      if (other.Str.Length != 0) {
        Str = other.Str;
      }
      inputs_.Add(other.inputs_);
      states_.Add(other.states_);
      roominfos_.Add(other.roominfos_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            Type = (global::GameProto.ServerEventCode) input.ReadEnum();
            break;
          }
          case 16: {
            Fid = input.ReadInt32();
            break;
          }
          case 26: {
            Str = input.ReadString();
            break;
          }
          case 34: {
            inputs_.AddEntriesFrom(input, _repeated_inputs_codec);
            break;
          }
          case 42: {
            states_.AddEntriesFrom(input, _repeated_states_codec);
            break;
          }
          case 50: {
            roominfos_.AddEntriesFrom(input, _repeated_roominfos_codec);
            break;
          }
        }
      }
    }

  }

  #endregion

}

#endregion Designer generated code
